# Generated by Django 5.0.6 on 2026-01-24 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksafety', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSafetyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Work Safety Category',
                'verbose_name_plural': 'Work Safety Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkSafetyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional document description')),
                ('file', models.FileField(help_text='Upload PDF, Word, or other document', upload_to='worksafety/')),
                ('version', models.CharField(default='1.0', help_text='e.g. 1.0, 1.1, 2.0', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('visible_to', models.CharField(choices=[('everyone', 'Everyone'), ('teamleaders', 'Team Leaders Only')], default='everyone', help_text='Control who can view this document', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='worksafety.worksafetycategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksafety_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Safety Document',
                'verbose_name_plural': 'Work Safety Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSafetyAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Document version at time of acknowledgement', max_length=20)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksafety_acks', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acks', to='worksafety.worksafetydocument')),
            ],
            options={
                'verbose_name': 'Work Safety Acknowledgement',
                'verbose_name_plural': 'Work Safety Acknowledgements',
                'ordering': ['-acknowledged_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSafetyEmergencyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_number', models.CharField(default='112', help_text='Emergency services number', max_length=50)),
                ('police_number', models.CharField(default='110', help_text='Police number', max_length=50)),
                ('company_contact_name', models.CharField(blank=True, help_text='Company emergency contact name', max_length=100)),
                ('company_contact_phone', models.CharField(blank=True, help_text='Company emergency contact phone', max_length=50)),
                ('quick_steps', models.TextField(help_text='Quick emergency action steps (3-6 bullet points, one per line)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_info_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Information',
                'verbose_name_plural': 'Emergency Information',
            },
        ),
        migrations.CreateModel(
            name='WorkSafetyIncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Describe what happened')),
                ('location', models.CharField(blank=True, help_text='Where did this occur?', max_length=200)),
                ('occurred_at', models.DateTimeField(help_text='When did this occur?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], default='open', max_length=20)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Report',
                'verbose_name_plural': 'Incident Reports',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='worksafetyacknowledgement',
            constraint=models.UniqueConstraint(fields=('document', 'user', 'version'), name='unique_document_user_version'),
        ),
    ]
