# Generated by Django 5.0.6 on 2025-10-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, help_text='Include country code, e.g. +216 12 345 678', max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='contacts/photos/')),
                ('is_teamleader', models.BooleanField(default=False)),
                ('seller_of_month_count', models.PositiveIntegerField(default=0)),
                ('icebar_of_month_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
