# Generated by Django 5.0.6 on 2025-10-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='joined_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
