# Generated by Django 5.0.6 on 2025-10-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('it', 'IT / Security'), ('hr', 'HR / Schedule'), ('management', 'Management'), ('complaint', 'Complaint'), ('other', 'Other')], default='general', max_length=24),
        ),
    ]
