# Generated by Django 5.0.6 on 2025-10-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TEAMLEADER', 'Teamleader'), ('SELLER', 'Seller')], default='SELLER', max_length=20),
        ),
    ]
