# Generated by Django 5.0.6 on 2026-01-24 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_participants_visible_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='responded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('going', 'Going'), ('maybe', 'Maybe'), ('not_going', 'Not Going')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_user_rsvp'),
        ),
    ]
